import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone13Mini1(),
        ]),
      ),
    );
  }
}

class Iphone13Mini1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white), // This color is covered by the gradient below
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 812,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, -0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF076653), const Color(0xFF0C342C)],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -72,
                top: -111,
                child: Container(
                  width: 347,
                  height: 923,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, -0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF1EA78A), const Color(0xFF0C4136)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(173.50),
                        topRight: Radius.circular(173.50),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 42,
                child: Container(
                  width: 347,
                  height: 858,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, -0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF14B997), const Color(0xFF095344)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(173.50),
                        topRight: Radius.circular(173.50),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -38,
                top: 319,
                child: Container(
                  width: 278,
                  height: 493,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.95, 0.06),
                      end: Alignment(0.10, 1.00),
                      colors: [const Color(0xFF0B4438), const Color(0xFF137963), const Color(0xFF1BAA8B)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(139),
                        topRight: Radius.circular(139),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 190,
                top: 516,
                child: Container(
                  width: 233,
                  height: 351,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, -0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF076653), const Color(0xFF0C342C)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(116.50),
                        topRight: Radius.circular(116.50),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -5,
                top: 0,
                child: Container(
                  width: 384,
                  height: 43,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 21,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(32),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              // Added "MATZIP" Text
              Positioned(
                left: 0, // Center horizontally
                right: 0,
                top: 330, // Estimated position above the subtitles
                child: Text(
                  'MATZIP',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 64, // Prominent font size
                    fontFamily: 'Pretendard', // Assuming this font is configured
                    fontWeight: FontWeight.w900, // Very bold, similar to image
                    letterSpacing: 1.2, // Slight letter spacing for visual appeal
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 422, // This might need slight adjustment after adding MATZIP title
                child: SizedBox(
                  width: 248,
                  height: 96,
                  child: Text(
                    'AI 매물 추천\n아파트 빅데이터 보고서\n아파트 미래가격 예측',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w600,
                      height: 1.78,
                      letterSpacing: -0.45,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}